spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/his?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 20000516song
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
shiro-redis:
  enabled: true
  redis-manager :
    host: 127.0.0.1:6379

neu:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
  expire: 604800
  header: Authorization

